name: Deploy Terraform to GCP

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.6.6

      - name: Set up GCP Credentials
        run: |
          echo "${{ secrets.GCP_SA_KEY_BASE64 }}" | base64 -d > gcp-key.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=${PWD}/gcp-key.json" >> $GITHUB_ENV
        working-directory: ./terraform

      - name: Zip Cloud Function
        run: zip -r function.zip /serverless/*

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform
        env:
          TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./terraform
        env:
          TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}